import type { Metadata } from 'next'
import DetailPage from '../components/DetailPage'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <DetailPage pageName="BLOG">{children}</DetailPage>
}
